<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ServicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 'category_id',

     * @return void
     */
    public function run()
    {
        DB::table('services')->insert([
            [
                'category_id' => '1',
                'name' => 'Deep skin cleansing',
                'description' => 'Skin care',
                'price' => '100000',
                'topServices' => '0',
                'image' => '/images/deep caeaning.jpg',
            ],
            [
                'category_id' => '1',
                'name' => 'Golden skin cleansing',
                'description' => 'Skin care',
                'price' => '150000',
                'topServices' => '1',
                'image' => '/images/deep caeaning.jpg',

            ],
            [
                'category_id' => '1',
                'name' => 'cleansing face+neck',
                'description' => 'Skin care',
                'price' => '125000',
                'topServices' => '0',
                'image' => '/images/deep caeaning.jpg',

            ],
            [
                'category_id' => '1',
                'name' => 'Back cleansing',
                'description' => 'Skin care',
                'price' => '150000',
                'topServices' => '0',
                'image' => '/images/back.jpeg',

            ],
            [
                'category_id' => '1',
                'name' => 'Hydrafacial for underarms',
                'description' => 'Skin care',
                'price' => '65000',
                'topServices' => '0',
                'image' => '/images/under.jpeg',
            ],
            [
                'category_id' => '1',
                'name' => 'Hand care',
                'description' => 'Skin care',
                'price' => '65000',
                'topServices' => '0',
                'image' => '/images/hand.jpeg',
            ],
            [
                'category_id' => '1',
                'name' => 'Meso dermapen',
                'description' => 'Skin care',
                'price' => '115000',
                'topServices' => '1',
                'image' => '/images/mesoDermapen.jpg',
            ],
            [
                'category_id' => '1',
                'name' => 'Meso stop acne',
                'description' => 'Skin care',
                'price' => '110000',
                'topServices' => '0',
                'image' => '/images/stop.jpeg',
            ],

            [
                'category_id' => '1',
                'name' => 'Plasma',
                'description' => 'Skin care',
                'price' => '80000',
                'topServices' => '0',
                'image' => '/images/plasmaa.jpeg',
            ],
            [
                'category_id' => '1',
                'name' => 'Plasma dermapen',
                'description' => 'Skin care',
                'price' => '130000',
                'topServices' => '0',
                'image' => '/images/Dermapen_y_Plasma.jpg',
            ],
            [
                'category_id' => '1',
                'name' => 'Hyaluronic acid',
                'description' => 'Skin care',
                'price' => '200000',
                'topServices' => '1',
                'image' => '/images/acid.jpeg',
            ],
            [
                'category_id' => '1',
                'name' => 'Meso cocktail',
                'description' => 'Skin care',
                'price' => '200000',
                'topServices' => '0',
                'image' => '/images/coc.jpeg',
            ],
            ////////////////
            [
                'category_id' => '2',
                'name' => 'Teeth cleaning + polish',
                'description' => 'Dental department',
                'price' => '60000',
                'topServices' => '0',
                'image' => '/images/teeth-cleaning.jpg',
            ],
            [
                'category_id' => '2',
                'name' => 'Teeth cleaning + scaling',
                'description' => 'Dental department',
                'price' => '60000',
                'topServices' => '0',
                'image' => '/images/scal.jpg',
            ],
            [
                'category_id' => '2',
                'name' => 'Composite fillings',
                'description' => 'Dental department',
                'price' => '150000',
                'topServices' => '1',
                'image' => '/images/comp.jpeg',
            ],
            [
                'category_id' => '2',
                'name' => 'Front root canal treatment ',
                'description' => 'Dental department',
                'price' => '200000',
                'topServices' => '0',
                'image' => '/images/scal.jpeg',
            ],
            [
                'category_id' => '2',
                'name' => 'Back root canal treatment ',
                'description' => 'Dental department',
                'price' => '400000',
                'topServices' => '0',
                'image' => '/images/root.jpg',
            ],
            [
                'category_id' => '2',
                'name' => 'Veneers per tooth',
                'description' => 'Dental department',
                'price' => '600000',
                'topServices' => '1',
                'image' => '/images/ven.jpeg',
            ],
            [
                'category_id' => '2',
                'name' => 'E-max veneer',
                'description' => 'Dental department',
                'price' => '600000',
                'topServices' => '1',
                'image' => '/images/ven.jpeg',
            ],
            [
                'category_id' => '2',
                'name' => 'Dental implant ',
                'description' => 'Dental department',
                'price' => '2000000',
                'topServices' => '0',
                'image' => '/images/plant.jpeg',
            ],
            [
                'category_id' => '2',
                'name' => 'Laser teeth whitening',
                'description' => 'Dental department',
                'price' => '550000',
                'topServices' => '0',
                'image' => '/images/teethcleaning.webp',
            ],
            [
                'category_id' => '2',
                'name' => 'Home teeth whitening',
                'description' => 'Dental department',
                'price' => '400000',
                'topServices' => '0',
                'image' => '/images/home.jpeg',
            ],
            ////////////////
            [
                'category_id' => '3',
                'name' => 'Nutrition consultation',
                'description' => 'Body health',
                'price' => '18000',
                'topServices' => '1',
                'image' => '/images/food.jpeg',
            ],
            [
                'category_id' => '3',
                'name' => 'Inbody',
                'description' => 'Body health',
                'price' => '25000',
                'topServices' => '0',
                'image' => '/images/body.jpg',
            ],
            [
                'category_id' => '3',
                'name' => 'Monthly diet',
                'description' => 'Body health',
                'price' => '80000',
                'topServices' => '0',
                'image' => '/images/diet.jpeg',
            ],
            [
                'category_id' => '3',
                'name' => 'Meso fat (3 sessions)',
                'description' => 'Body health',
                'price' => '330000',
                'topServices' => '0',
                'image' => '/images/mesofat.webp',
            ],
            [
                'category_id' => '3',
                'name' => 'Meso fat (6 sessions)',
                'description' => 'Body health',
                'price' => '620000',
                'topServices' => '0',
                'image' => '/images/mesofat.webp',
            ],
            [
                'category_id' => '3',
                'name' => 'Lemon Bottle',
                'description' => 'Body health',
                'price' => '600000',
                'topServices' => '1',
                'image' => '/images/Lemon-Bottle-Fat.jpeg',
            ],
            //////////////////
            [
                'category_id' => '4',
                'name' => 'Meso under eye',
                'description' => 'Cosmetic department',
                'price' => '550000',
                'topServices' => '0',
                'image' => '/images/undereye.jpeg',
            ],
            [
                'category_id' => '4',
                'name' => 'Profhilo injection',
                'description' => 'Cosmetic department',
                'price' => '750000',
                'topServices' => '1',
                'image' => '/images/profa.jpeg',
            ],
            [
                'category_id' => '4',
                'name' => 'Kiara reju',
                'description' => 'Cosmetic department',
                'price' => '750000',
                'topServices' => '0',
                'image' => '/images/kiara.jpeg',
            ],
            [
                'category_id' => '4',
                'name' => 'Korean filler',
                'description' => 'Cosmetic department',
                'price' => '750000',
                'topServices' => '0',
                'image' => '/images/filler.jpeg',
            ],
            [
                'category_id' => '4',
                'name' => 'German filler',
                'description' => 'Cosmetic department',
                'price' => '1000000',
                'topServices' => '1',
                'image' => '/images/filler.jpeg',
            ],
            [
                'category_id' => '4',
                'name' => 'Botox',
                'description' => 'Cosmetic department',
                'price' => '600000',
                'topServices' => '0',
                'image' => '/images/botox.jpeg',
            ],
            [
                'category_id' => '4',
                'name' => 'Botox sweating',
                'description' => 'Cosmetic department',
                'price' => '900000',
                'topServices' => '0',
                'image' => '/images/under.jpeg',
            ],
            [
                'category_id' => '5',
                'name' => 'Face',
                'description' => 'Hair removal',
                'price' => '48000',
                'topServices' => '0',
                'image' => '/images/cynosure.jpeg',
            ],
            [
                'category_id' => '6',
                'name' => 'Face',
                'description' => 'Hair removal',
                'price' => '20000',
                'topServices' => '0',
                'image' => '/images/lumenis.jpeg',
            ],
            [
                'category_id' => '7',
                'name' => 'Face',
                'description' => 'Hair removal',
                'price' => '24000',
                'topServices' => '0',
                'image' => '/images/ami.jpeg',
            ],

            [
                'category_id' => '5',
                'name' => 'underarm',
                'description' => 'Hair removal',
                'price' => '25000',
                'topServices' => '0',
                'image' => '/images/cynosure.jpeg',
            ],
            [
                'category_id' => '6',
                'name' => 'underarm',
                'description' => 'Hair removal',
                'price' => '17000',
                'topServices' => '0',
                'image' => '/images/lumenis.jpeg',
            ],
            [
                'category_id' => '7',
                'name' => 'underarm',
                'description' => 'Hair removal',
                'price' => '17000',
                'topServices' => '0',
                'image' => '/images/ami.jpeg',
            ],
            [
                'category_id' => '5',
                'name' => 'Stomach',
                'description' => 'Hair removal',
                'price' => '75000',
                'topServices' => '0',
                'image' => '/images/cynosure.jpeg',
            ],
            [
                'category_id' => '6',
                'name' => 'Stomach',
                'description' => 'Hair removal',
                'price' => '40000',
                'topServices' => '0',
                'image' => '/images/lumenis.jpeg',
            ],
            [
                'category_id' => '7',
                'name' => 'Stomach',
                'description' => 'Hair removal',
                'price' => '50000',
                'topServices' => '0',
                'image' => '/images/ami.jpeg',
            ],
            [
                'category_id' => '5',
                'name' => 'Back',
                'description' => 'Hair removal',
                'price' => '85000',
                'topServices' => '0',
                'image' => '/images/cynosure.jpeg',
            ],
            [
                'category_id' => '6',
                'name' => 'Back',
                'description' => 'Hair removal',
                'price' => '58000',
                'topServices' => '0',
                'image' => '/images/lumenis.jpeg',
            ],
            [
                'category_id' => '7',
                'name' => 'Back',
                'description' => 'Hair removal',
                'price' => '48000',
                'topServices' => '0',
                'image' => '/images/ami.jpeg',
            ],
            [
                'category_id' => '5',
                'name' => 'Arms',
                'description' => 'Hair removal',
                'price' => '115000',
                'topServices' => '0',
                'image' => '/images/cynosure.jpeg',
            ],
            [
                'category_id' => '6',
                'name' => 'Arms',
                'description' => 'Hair removal',
                'price' => '72000',
                'topServices' => '0',
                'image' => '/images/lumenis.jpeg',
            ],
            [
                'category_id' => '7',
                'name' => 'Arms',
                'description' => 'Hair removal',
                'price' => '85000',
                'topServices' => '0',
                'image' => '/images/ami.jpeg',
            ],
            [
                'category_id' => '5',
                'name' => 'Legs',
                'description' => 'Hair removal',
                'price' => '195000',
                'topServices' => '0',
                'image' => '/images/cynosure.jpeg',
            ],
            [
                'category_id' => '6',
                'name' => 'Legs',
                'description' => 'Hair removal',
                'price' => '98000',
                'topServices' => '0',
                'image' => '/images/lumenis.jpeg',
            ],
            [
                'category_id' => '7',
                'name' => 'Legs',
                'description' => 'Hair removal',
                'price' => '105000',
                'topServices' => '0',
                'image' => '/images/ami.jpeg',
            ],
            [
                'category_id' => '5',
                'name' => 'Mini laser',
                'description' => 'Forearms&Legs&bikini&Mustaches',
                'price' => '232000',
                'topServices' => '0',
                'image' => '/images/cynosure.jpeg',
            ],
            [
                'category_id' => '6',
                'name' => 'Mini laser',
                'description' => 'Forearms&Legs&bikini&Mustaches',
                'price' => '118000',
                'topServices' => '0',
                'image' => '/images/lumenis.jpeg',
            ],
            [
                'category_id' => '7',
                'name' => 'Mini laser',
                'description' => 'Forearms&Legs&bikini&Mustaches',
                'price' => '150000',
                'topServices' => '0',
                'image' => '/images/ami.jpeg',
            ],
            [
                'category_id' => '5',
                'name' => 'Full body',
                'description' => 'Hair removal',
                'price' => '650000',
                'topServices' => '0',
                'image' => '/images/cynosure.jpeg',
            ],
            [
                'category_id' => '6',
                'name' => 'Full body',
                'description' => 'Hair removal',
                'price' => '345000',
                'topServices' => '0',
                'image' => '/images/lumenis.jpeg',
            ],
            [
                'category_id' => '7',
                'name' => 'Full body',
                'description' => 'Hair removal',
                'price' => '425000',
                'topServices' => '0',
                'image' => '/images/ami.jpeg',
            ],


        ]);
    }
}
